### ISSUE TITLE
OpenShift SDN does not have configuration options for the self IP

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-sdn#84] opened 2015-06-09 04:16 UTC
When there are multiple IPs for a hostname the value can be incorrect.

**Comment by smarterclayton** [comment] 2015-06-09 04:16
There should be a config value for the node and for the master for the IP for SDN to bind to.

**Comment by nak3** [comment] 2015-06-09 05:06
I think it is caused by golang's `net.LookupIP` here.

https://github.com/openshift/openshift-sdn/blob/9b6e4a3058a679896655527b9001f43e4f5debf6/ovssubnet/common.go#L151-L156

You can see that `addrs[0]` can be what you are not expected with following code after you add several hostname and IP to your `/etc/hosts`.

~~~
package main

import (
	"fmt"
	"net"
	"strings"
)

func main() {
	addresses, err := net.LookupIP("ose3.master.example.com")
	fmt.Println(addresses, err)

	for i := 0; i < len(addresses); i++ {

		segments := strings.SplitAfter(addresses[i].String(), " ")

		fmt.Printf("IP address #%d : %s \n", i, segments)
	}

}
~~~

**Comment by nak3** [comment] 2015-06-09 05:07
Yes, config value will solve it.

**Comment by sdodson** [comment] 2015-07-23 14:25
If a node's ip address changes for any reason the sdn is not currently updating tunnel destinations with that new ip address. If we add this as a configuration option we should make sure that we update hostsubnets appropriately.

Happy to open this as a separate issue but I figured it's essentially allowing the hostIP to be configured.

**Comment by rajatchopra** [comment] 2015-07-23 18:27
@sdodson That update error can be fixed (PR coming). The question is - will the node object in kubernetes change when a node changes its IP address?

Also, should we just obtain the IP address of the node from Node.NodeStatus.Addresses[0] ?

@pravisankar, FYI

**Comment by rajatchopra** [comment] 2015-08-03 21:18
The current proposal is to obtain the 'IP address' from node config (new field). This will allow us to separate overlay traffic from master-node traffic when two NICs are available on a node.

**Comment by sdodson** [comment] 2015-08-14 13:35
@pravisankar was this fixed via other changes?

**Comment by pravisankar** [comment] 2015-08-18 00:57
@sdodson 
PR https://github.com/openshift/origin/pull/4056 (merged) will fix the subnet when the node IP changes.
I'm working on another PR where you can specify node IP in the node configuration, this will be helpful in the case where the node has multiple IPs.

**Comment by pravisankar** [comment] 2015-09-08 22:21
Fixed in https://github.com/openshift/origin/pull/4459

**Closed by pravisankar** 2015-09-08 22:21 UTC
Labels: enhancement
